# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-quartermaster

# >> macros
# << macros

Summary:    Quartermaster
Version:    0.3.1
Release:    1
Group:      Qt/Qt
License:    MIT
URL:        https://github.com/black-sheep-dev/harbour-quartermaster
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-quartermaster.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   sailfishsecretsdaemon-secretsplugins-default
Requires:   nemo-qml-plugin-dbus-qt5
Requires:   nemo-qml-plugin-notifications-qt5
Requires:   qtmozembed-qt5
Requires:   sailfish-components-webview-qt5
Requires:   sailfish-components-webview-qt5-popups
Requires:   sailfish-components-webview-qt5-pickers
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5WebSockets) >= 5.5.1
BuildRequires:  pkgconfig(sailfishsecrets)
BuildRequires:  pkgconfig(nemodbus)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  pkgconfig(qt5embedwidget) >= 1.14.9
BuildRequires:  pkgconfig(keepalive)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  sailfish-mdm-devel
BuildRequires:  desktop-file-utils

%description
Quartermaster is a native Sailfish OS Home Assistant client

%if "%{?vendor}" == "chum"
PackageName: Quartermaster
Type: desktop-application
Categories:
  - Utility
Custom:
  DescriptionMD: https://github.com/black-sheep-dev/harbour-quartermaster/raw/master/README.md
  Repo: https://github.com/black-sheep-dev/harbour-quartermaster/
Icon: https://raw.githubusercontent.com/black-sheep-dev/harbour-quartermaster/master/icons/harbour-quartermaster.svg
Screenshots:
    - https://github.com/black-sheep-dev/harbour-quartermaster/raw/master/metadata/screenshot01.png
Url:
  Donation: https://www.paypal.com/paypalme/nubecula/1
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
